Repository falcosecurity/falco-talon, pull requests merged in 2024-07, with the labels that each got.

#367 feat(helm): Support ServiceMonitor CRD
  deployment/helm/templates/servicemonitor.yaml
  deployment/helm/values.yaml
Labels: enhancement

#369 change graph by a mermaid flow chart
  README.md
Labels: documentation, enhancement

#330 Add otel
  .gitignore
  actionners/actionners.go
  actionners/kubernetes/drain/drain.go
  cmd/server.go
  config_example.yaml
  configuration/configuration.go
  deployment/compose/docker-compose.yaml
  deployment/compose/grafana/grafana.ini
  deployment/compose/grafana/provisioning/dashboards/sample-node.json
  deployment/compose/grafana/provisioning/datasources/default.yaml
  deployment/compose/otel/collector-config.yaml
  deployment/compose/prometheus/prometheus.yaml
  go.mod
  go.sum
  internal/context/context.go
  internal/events/events.go
  internal/handler/handler.go
  internal/nats/nats.go
  internal/otlp/metrics/metrics.go
  internal/otlp/traces/traces.go
  notifiers/notifiers.go
Labels: new feature

#379 add stage field for the logs of notications/actions
  notifiers/notifiers.go
  utils/utils.go
Labels: bug
