Repository falcosecurity/falco-talon, pull requests merged in 2024-10, with the labels that each got.

#459 change workflow to allow actionner to also delete pods
  actionners/kubernetes/drain/drain.go
  actionners/kubernetes/terminate/terminate.go
  internal/kubernetes/client/client.go
  rules.yaml
  utils/utils.go
Labels: enhancement

#475 docs(README.md): add badges
  README.md
Labels: area/config, dco-signoff: yes, approved, size/XS, lgtm

#476 different fixes post transfer to the falcosecurity org
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/charts.yml
  .github/workflows/main.yml
  .goreleaser.yml
  OWNERS
  README.md
  mageFile.go
Labels: area/config, kind/cleanup, kind/documentation, dco-signoff: yes, approved, lgtm, size/L

#477 fix the credentials for Dockerhub + fix variables for the Version info
  .github/workflows/main.yml
  .github/workflows/release.yml
  mageFile.go
Labels: area/build, area/config, kind/cleanup, kind/failing-test, dco-signoff: yes, approved, lgtm, size/M

#478 fix the paths to the imported modules
  .golangci.yml
  README.md
  actionners/actionners.go
  actionners/aws/lambda/lambda.go
  actionners/calico/networkpolicy/networkpolicy.go
  actionners/cilium/networkpolicy/networkpolicy.go
  actionners/kubernetes/cordon/cordon.go
  actionners/kubernetes/delete/delete.go
  actionners/kubernetes/download/download.go
  actionners/kubernetes/drain/drain.go
  actionners/kubernetes/exec/exec.go
  actionners/kubernetes/label/label.go
  actionners/kubernetes/log/log.go
  actionners/kubernetes/networkpolicy/networkpolicy.go
  actionners/kubernetes/script/script.go
  actionners/kubernetes/tcpdump/tcpdump.go
  actionners/kubernetes/terminate/terminate.go
  cmd/actionners.go
  cmd/notifiers.go
  cmd/outputs.go
  cmd/root.go
  cmd/rules.go
  cmd/server.go
  cmd/version.go
  config_example.yaml
  configuration/configuration.go
  deployment/helm/Chart.yaml
  deployment/helm/README.gotmpl
  deployment/helm/README.md
  deployment/helm/values.yaml
  go.mod
  go.sum
  internal/aws/checks/checks.go
  internal/aws/client/client.go
  internal/calico/client/client.go
  internal/cilium/client/client.go
  internal/context/aws/aws.go
  internal/context/context.go
  internal/context/kubernetes/kubernetes.go
  internal/handler/handler.go
  internal/kubernetes/checks/checks.go
  internal/kubernetes/client/client.go
  internal/minio/client/client.go
  internal/otlp/metrics/metrics.go
  internal/otlp/traces/traces.go
  internal/rules/rules.go
  mageFile.go
  main.go
  notifiers/elasticsearch/elasticsearch.go
  notifiers/http/client.go
  notifiers/k8sevents/k8sevents.go
  notifiers/loki/loki.go
  notifiers/notifiers.go
  notifiers/slack/slack.go
  notifiers/smtp/smtp.go
  notifiers/webhook/webhook.go
  outputs/aws/s3/s3.go
  outputs/file/file.go
  outputs/minio/minio.go
  outputs/outputs.go
Labels: kind/cleanup, kind/failing-test, dco-signoff: yes, approved, lgtm, size/XXL

#479 fix wrong owner in github
  .goreleaser.yml
Labels: area/config, kind/cleanup, kind/failing-test, dco-signoff: yes, approved, size/XS, lgtm
