Repository falcosecurity/falco-talon, pull requests merged in 2024-09, with the labels that each got.

#412 add subcommand for actionners + outputs + notifiers
  .gitignore
  .golangci.yml
  actionners/actionners.go
  actionners/aws/lambda/lambda.go
  actionners/calico/networkpolicy/networkpolicy.go
  actionners/cilium/networkpolicy/networkpolicy.go
  actionners/kubernetes/cordon/cordon.go
  actionners/kubernetes/delete/delete.go
  actionners/kubernetes/download/download.go
  actionners/kubernetes/drain/drain.go
  actionners/kubernetes/exec/exec.go
  actionners/kubernetes/label/label.go
  actionners/kubernetes/log/log.go
  actionners/kubernetes/networkpolicy/networkpolicy.go
  actionners/kubernetes/script/script.go
  actionners/kubernetes/tcpdump/tcpdump.go
  actionners/kubernetes/terminate/terminate.go
  cmd/actionners.go
  cmd/notifiers.go
  cmd/outputs.go
  cmd/root.go
  cmd/rules.go
  cmd/server.go
  configuration/configuration.go
  deployment/compose/docker-compose.yaml
  deployment/compose/grafana/provisioning/datasources/default.yaml
  deployment/compose/loki/loki.yaml
  go.mod
  go.sum
  internal/aws/checks/checks.go
  internal/aws/client/client.go
  internal/kubernetes/checks/checks.go
  internal/kubernetes/client/client.go
  internal/minio/client/client.go
  internal/models/models.go
  internal/otlp/metrics/metrics.go
  internal/rules/rules.go
  notifiers/elasticsearch/elasticsearch.go
  notifiers/k8sevents/k8sevents.go
  notifiers/loki/loki.go
  notifiers/notifiers.go
  notifiers/slack/slack.go
  notifiers/smtp/smtp.go
  notifiers/webhook/webhook.go
  outputs/aws/s3/s3.go
  outputs/file/file.go
  outputs/minio/minio.go
  outputs/model/model.go
  outputs/outputs.go
  utils/utils.go
Labels: enhancement, new feature

#418 add loop to check the state of the ephemeralcontainer
  internal/kubernetes/client/client.go
Labels: bug

#426 use a smaller image for the tcpdump for a quicker cold start (pull)
  actionners/kubernetes/tcpdump/tcpdump.go
  cmd/actionners.go
  internal/kubernetes/client/client.go
Labels: enhancement

#427 Refactor drain to watcher goroutine
  actionners/kubernetes/drain/drain.go
  actionners/kubernetes/terminate/terminate.go
  deployment/helm/templates/deployment.yaml
  go.mod
  go.sum
  internal/kubernetes/client/client.go
  rules.yaml
  utils/utils.go
Labels: enhancement

#457 fix various panics + fix label with a / in the key
  actionners/calico/networkpolicy/networkpolicy.go
  actionners/cilium/networkpolicy/networkpolicy.go
  actionners/kubernetes/label/label.go
  cmd/rules.go
  configuration/configuration.go
  internal/context/aws/aws.go
  internal/context/context.go
  internal/context/kubernetes/kubernetes.go
  internal/events/events.go
  internal/kubernetes/client/client.go
  internal/models/models.go
  internal/rules/rules.go
  notifiers/elasticsearch/elasticsearch.go
  notifiers/http/client.go
  notifiers/k8sevents/k8sevents.go
  notifiers/loki/loki.go
  notifiers/notifiers.go
  notifiers/slack/slack.go
  notifiers/smtp/smtp.go
  notifiers/webhook/webhook.go
  utils/utils.go
Labels: bug
