Repository falcosecurity/falco-talon, pull requests merged in 2024-08, with the labels that each got.

#384 update docker compose stack + add a prefix to prom metrics
  .gitignore
  README.md
  config_example.yaml
  deployment/compose/docker-compose.yaml
  deployment/compose/grafana/provisioning/datasources/default.yaml
  deployment/compose/otel/collector-config.yaml
  deployment/compose/otel/otel-collector.yaml
  deployment/compose/prometheus/prometheus.yaml
  deployment/compose/tempo/tempo.yaml
  deployment/helm/templates/secrets.yaml
  internal/otlp/metrics/metrics.go
Labels: enhancement

#385 export metrics trough OTLP
  cmd/server.go
  config_example.yaml
  configuration/configuration.go
  go.mod
  go.sum
  internal/otlp/metrics/metrics.go
  internal/otlp/traces/traces.go
Labels: new feature

#396 improve contexts and attributes for the spans
  actionners/actionners.go
  actionners/aws/lambda/lambda.go
  actionners/calico/networkpolicy/networkpolicy.go
  actionners/cilium/networkpolicy/networkpolicy.go
  actionners/kubernetes/cordon/cordon.go
  actionners/kubernetes/delete/delete.go
  actionners/kubernetes/download/download.go
  actionners/kubernetes/drain/drain.go
  actionners/kubernetes/exec/exec.go
  actionners/kubernetes/label/label.go
  actionners/kubernetes/log/log.go
  actionners/kubernetes/networkpolicy/networkpolicy.go
  actionners/kubernetes/script/script.go
  actionners/kubernetes/tcpdump/tcpdump.go
  actionners/kubernetes/terminate/terminate.go
  cmd/check.go
  cmd/server.go
  deployment/compose/docker-compose.yaml
  deployment/helm/templates/secrets.yaml
  deployment/helm/values.yaml
  internal/context/context.go
  internal/handler/handler.go
  internal/otlp/metrics/metrics.go
  internal/otlp/traces/traces.go
  internal/rules/rules.go
  notifiers/k8sevents/k8sevents.go
  notifiers/loki/loki.go
  notifiers/notifiers.go
  notifiers/slack/slack.go
  notifiers/smtp/smtp.go
  notifiers/smtp/templates.go
  outputs/aws/s3/s3.go
  outputs/file/file.go
  outputs/minio/minio.go
  rules.yaml
  utils/utils.go
Labels: enhancement

#400 add match span + config for tail_sampling in the otel collector
  actionners/actionners.go
  deployment/compose/docker-compose.yaml
  deployment/compose/otel/otel-collector.yaml
  internal/rules/rules.go
Labels: enhancement

#401 add rbac for to allow to get the logs + fix some values
  deployment/helm/templates/deployment.yaml
  deployment/helm/templates/rbac.yaml
  deployment/helm/templates/secrets.yaml
  deployment/helm/values.yaml
Labels: bug

#409 add subcommand rules
  cmd/root.go
  cmd/rules.go
  cmd/server.go
  internal/handler/handler.go
Labels: enhancement
